using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using AutocompleteMenuNS;
namespace WiiJoyScripter
{
    public partial class Form3 : Form
    {
        public Form1 form1;
        string[] keywords = { "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while", "add", "alias", "ascending", "descending", "dynamic", "from", "get", "global", "group", "into", "join", "let", "orderby", "partial", "remove", "select", "set", "value", "var", "where", "yield",
            "void",
            "bool",
            "int",
            "float",
            "double",
            "Double",
            "List",
            "[",
            "]",
            "if",
            "input",
            "/* */",
            "this",
            "input",
            "mWSNunchuckStateRawJoystickX",
            "mWSNunchuckStateRawJoystickY",
            "mWSNunchuckStateRawValuesX",
            "mWSNunchuckStateRawValuesY",
            "mWSNunchuckStateRawValuesZ",
            "mWSNunchuckStateC",
            "mWSNunchuckStateZ",
            "mWSButtonStateIRX",
            "mWSButtonStateIRY",
            "mWSButtonStateA",
            "mWSButtonStateB",
            "mWSButtonStateMinus",
            "mWSButtonStateHome",
            "mWSButtonStatePlus",
            "mWSButtonStateOne",
            "mWSButtonStateTwo",
            "mWSButtonStateUp",
            "mWSButtonStateDown",
            "mWSButtonStateLeft",
            "mWSButtonStateRight",
            "mWSRawValuesX",
            "mWSRawValuesY",
            "mWSRawValuesZ",
            "EulerAnglesX",
            "EulerAnglesY",
            "EulerAnglesZ",
            "DirectAnglesX",
            "DirectAnglesY",
            "DirectAnglesZ",
            "camx",
            "camy",
            "EulerAnglesLeftX",
            "EulerAnglesLeftY",
            "EulerAnglesLeftZ",
            "DirectAnglesLeftX",
            "DirectAnglesLeftY",
            "DirectAnglesLeftZ",
            "EulerAnglesRightX",
            "EulerAnglesRightY",
            "EulerAnglesRightZ",
            "DirectAnglesRightX",
            "DirectAnglesRightY",
            "DirectAnglesRightZ",
            "LeftButtonSHOULDER_1",
            "LeftButtonMINUS",
            "LeftButtonCAPTURE",
            "LeftButtonDPAD_UP",
            "LeftButtonDPAD_LEFT",
            "LeftButtonDPAD_DOWN",
            "LeftButtonDPAD_RIGHT",
            "LeftButtonSTICK",
            "RightButtonDPAD_DOWN",
            "LeftButtonSL",
            "LeftButtonSR",
            "GetStickLeftX",
            "GetStickLeftY",
            "RightButtonPLUS",
            "RightButtonDPAD_RIGHT",
            "RightButtonHOME",
            "RightButtonSHOULDER_1",
            "RightButtonDPAD_LEFT",
            "RightButtonDPAD_UP",
            "RightButtonSTICK",
            "RightButtonSL",
            "RightButtonSR",
            "RightButtonSHOULDER_2",
            "LeftButtonSHOULDER_2",
            "GetStickRightX",
            "GetStickRightY",
            "GetAccelX",
            "GetAccelY",
            "GetAccelZ",
            "GetAccelRightX",
            "GetAccelRightY",
            "GetAccelRightZ",
            "GetAccelLeftX",
            "GetAccelLeftY",
            "GetAccelLeftZ",
            "watchM",
            "_Valuechanged[]",
            "System.Collections.Generic.List<double>",
            "foreach",
            "return ",
            "Keys",
            "(Keys)",
            "System.Windows.Forms.Screen.PrimaryScreen.Bounds.Width",
            "System.Windows.Forms.Screen.PrimaryScreen.Bounds.Height",
            "System.Windows.Forms.Cursor.Position",
            "System.Drawing.Point",
            "SetPhysicalCursorPos",
            "SetCaretPos",
            "SetCursorPos",
            "(int)",
            "MouseMW3",
            "MouseBrink",
            "LeftClick()",
            "LeftClickF()",
            "RightClick()",
            "RightClickF()",
            "MiddleClick()",
            "MiddleClickF()",
            "WheelUpF()",
            "WheelDownF()",
            "SimulateKeyDown",
            "SimulateKeyUp",
            "SimulateKeyDownArrows",
            "SimulateKeyUpArrows",
            "MoveMouseTo",
            "MoveMouseBy",
            "SendMouseEventButtonLeft()",
            "SendMouseEventButtonLeftF()",
            "SendMouseEventButtonRight()",
            "SendMouseEventButtonRightF()",
            "SendMouseEventButtonMiddle()",
            "SendMouseEventButtonMiddleF()",
            "SendMouseEventButtonWheelUp()",
            "SendMouseEventButtonWheelDown()",
            "SendKey",
            "SendKeyF",
            "SendKeyArrows",
            "SendKeyArrowsF",
            "VK_LBUTTON", "S_LBUTTON",
            "VK_RBUTTON", "S_RBUTTON",
            "VK_CANCEL", "S_CANCEL",
            "VK_MBUTTON", "S_MBUTTON",
            "VK_XBUTTON1", "S_XBUTTON1",
            "VK_XBUTTON2", "S_XBUTTON2",
            "VK_BACK", "S_BACK",
            "VK_Tab", "S_Tab",
            "VK_CLEAR", "S_CLEAR",
            "VK_Return", "S_Return",
            "VK_SHIFT", "S_SHIFT",
            "VK_CONTROL", "S_CONTROL",
            "VK_MENU", "S_MENU",
            "VK_PAUSE", "S_PAUSE",
            "VK_CAPITAL", "S_CAPITAL",
            "VK_KANA", "S_KANA",
            "VK_HANGEUL", "S_HANGEUL",
            "VK_HANGUL", "S_HANGUL",
            "VK_JUNJA", "S_JUNJA",
            "VK_FINAL", "S_FINAL",
            "VK_HANJA", "S_HANJA",
            "VK_KANJI", "S_KANJI",
            "VK_Escape", "S_Escape",
            "VK_CONVERT", "S_CONVERT",
            "VK_NONCONVERT", "S_NONCONVERT",
            "VK_ACCEPT", "S_ACCEPT",
            "VK_MODECHANGE", "S_MODECHANGE",
            "VK_Space", "S_Space",
            "VK_PRIOR", "S_PRIOR",
            "VK_NEXT", "S_NEXT",
            "VK_END", "S_END",
            "VK_HOME", "S_HOME",
            "VK_LEFT", "S_LEFT",
            "VK_UP", "S_UP",
            "VK_RIGHT", "S_RIGHT",
            "VK_DOWN", "S_DOWN",
            "VK_SELECT", "S_SELECT",
            "VK_PRINT", "S_PRINT",
            "VK_EXECUTE", "S_EXECUTE",
            "VK_SNAPSHOT", "S_SNAPSHOT",
            "VK_INSERT", "S_INSERT",
            "VK_DELETE", "S_DELETE",
            "VK_HELP", "S_HELP",
            "VK_APOSTROPHE", "S_APOSTROPHE",
            "VK_0", "S_0",
            "VK_1", "S_1",
            "VK_2", "S_2",
            "VK_3", "S_3",
            "VK_4", "S_4",
            "VK_5", "S_5",
            "VK_6", "S_6",
            "VK_7", "S_7",
            "VK_8", "S_8",
            "VK_9", "S_9",
            "VK_A", "S_A",
            "VK_B", "S_B",
            "VK_C", "S_C",
            "VK_D", "S_D",
            "VK_E", "S_E",
            "VK_F", "S_F",
            "VK_G", "S_G",
            "VK_H", "S_H",
            "VK_I", "S_I",
            "VK_J", "S_J",
            "VK_K", "S_K",
            "VK_L", "S_L",
            "VK_M", "S_M",
            "VK_N", "S_N",
            "VK_O", "S_O",
            "VK_P", "S_P",
            "VK_Q", "S_Q",
            "VK_R", "S_R",
            "VK_S", "S_S",
            "VK_T", "S_T",
            "VK_U", "S_U",
            "VK_V", "S_V",
            "VK_W", "S_W",
            "VK_X", "S_X",
            "VK_Y", "S_Y",
            "VK_Z", "S_Z",
            "VK_LWIN", "S_LWIN",
            "VK_RWIN", "S_RWIN",
            "VK_APPS", "S_APPS",
            "VK_SLEEP", "S_SLEEP",
            "VK_NUMPAD0", "S_NUMPAD0",
            "VK_NUMPAD1", "S_NUMPAD1",
            "VK_NUMPAD2", "S_NUMPAD2",
            "VK_NUMPAD3", "S_NUMPAD3",
            "VK_NUMPAD4", "S_NUMPAD4",
            "VK_NUMPAD5", "S_NUMPAD5",
            "VK_NUMPAD6", "S_NUMPAD6",
            "VK_NUMPAD7", "S_NUMPAD7",
            "VK_NUMPAD8", "S_NUMPAD8",
            "VK_NUMPAD9", "S_NUMPAD9",
            "VK_MULTIPLY", "S_MULTIPLY",
            "VK_ADD", "S_ADD",
            "VK_SEPARATOR", "S_SEPARATOR",
            "VK_SUBTRACT", "S_SUBTRACT",
            "VK_DECIMAL", "S_DECIMAL",
            "VK_DIVIDE", "S_DIVIDE",
            "VK_F1", "S_F1",
            "VK_F2", "S_F2",
            "VK_F3", "S_F3",
            "VK_F4", "S_F4",
            "VK_F5", "S_F5",
            "VK_F6", "S_F6",
            "VK_F7", "S_F7",
            "VK_F8", "S_F8",
            "VK_F9", "S_F9",
            "VK_F10", "S_F10",
            "VK_F11", "S_F11",
            "VK_F12", "S_F12",
            "VK_F13", "S_F13",
            "VK_F14", "S_F14",
            "VK_F15", "S_F15",
            "VK_F16", "S_F16",
            "VK_F17", "S_F17",
            "VK_F18", "S_F18",
            "VK_F19", "S_F19",
            "VK_F20", "S_F20",
            "VK_F21", "S_F21",
            "VK_F22", "S_F22",
            "VK_F23", "S_F23",
            "VK_F24", "S_F24",
            "VK_NUMLOCK", "S_NUMLOCK",
            "VK_SCROLL", "S_SCROLL",
            "VK_LeftShift", "S_LeftShift",
            "VK_RightShift", "S_RightShift",
            "VK_LeftControl", "S_LeftControl",
            "VK_RightControl", "S_RightControl",
            "VK_LMENU", "S_LMENU",
            "VK_RMENU", "S_RMENU",
            "VK_BROWSER_BACK", "S_BROWSER_BACK",
            "VK_BROWSER_FORWARD", "S_BROWSER_FORWARD",
            "VK_BROWSER_REFRESH", "S_BROWSER_REFRESH",
            "VK_BROWSER_STOP", "S_BROWSER_STOP",
            "VK_BROWSER_SEARCH", "S_BROWSER_SEARCH",
            "VK_BROWSER_FAVORITES", "S_BROWSER_FAVORITES",
            "VK_BROWSER_HOME", "S_BROWSER_HOME",
            "VK_VOLUME_MUTE", "S_VOLUME_MUTE",
            "VK_VOLUME_DOWN", "S_VOLUME_DOWN",
            "VK_VOLUME_UP", "S_VOLUME_UP",
            "VK_MEDIA_NEXT_TRACK", "S_MEDIA_NEXT_TRACK",
            "VK_MEDIA_PREV_TRACK", "S_MEDIA_PREV_TRACK",
            "VK_MEDIA_STOP", "S_MEDIA_STOP",
            "VK_MEDIA_PLAY_PAUSE", "S_MEDIA_PLAY_PAUSE",
            "VK_LAUNCH_MAIL", "S_LAUNCH_MAIL",
            "VK_LAUNCH_MEDIA_SELECT", "S_LAUNCH_MEDIA_SELECT",
            "VK_LAUNCH_APP1", "S_LAUNCH_APP1",
            "VK_LAUNCH_APP2", "S_LAUNCH_APP2",
            "VK_OEM_1", "S_OEM_1",
            "VK_OEM_PLUS", "S_OEM_PLUS",
            "VK_OEM_COMMA", "S_OEM_COMMA",
            "VK_OEM_MINUS", "S_OEM_MINUS",
            "VK_OEM_PERIOD", "S_OEM_PERIOD",
            "VK_OEM_2", "S_OEM_2",
            "VK_OEM_3", "S_OEM_3",
            "VK_OEM_4", "S_OEM_4",
            "VK_OEM_5", "S_OEM_5",
            "VK_OEM_6", "S_OEM_6",
            "VK_OEM_7", "S_OEM_7",
            "VK_OEM_8", "S_OEM_8",
            "VK_OEM_102", "S_OEM_102",
            "VK_PROCESSKEY", "S_PROCESSKEY",
            "VK_PACKET", "S_PACKET",
            "VK_ATTN", "S_ATTN",
            "VK_CRSEL", "S_CRSEL",
            "VK_EXSEL", "S_EXSEL",
            "VK_EREOF", "S_EREOF",
            "VK_PLAY", "S_PLAY",
            "VK_ZOOM", "S_ZOOM",
            "VK_NONAME", "S_NONAME",
            "VK_PA1", "S_PA1",
            "VK_OEM_CLEAR", "S_OEM_CLEAR"
            };
        string[] methods = { "ToString()",
                "RemoveAt(0)",
                "Add",
                "MoveMouseTo",
                "MoveMouseBy",
                "SendLeftClick",
                "SendLeftClickF",
                "SendRightClick",
                "SendRightClickF",
                "SendMiddleClick",
                "SendMiddleClickF",
                "SendWheelUp",
                "SendWheelDown",
                "SendKey",
                "SendKeyF",
                "Escape",
                "One",
                "Two",
                "Three",
                "Four",
                "Five",
                "Six",
                "Seven",
                "Eight",
                "Nine",
                "Zero",
                "DashUnderscore",
                "PlusEquals",
                "Backspace",
                "Tab",
                "A",
                "Z",
                "E",
                "R",
                "T",
                "Y",
                "U",
                "I",
                "O",
                "P",
                "OpenBracketBrace",
                "CloseBracketBrace",
                "Enter",
                "Control",
                "Q",
                "S",
                "D",
                "F",
                "G",
                "H",
                "J",
                "K",
                "L",
                "SemicolonColon",
                "SingleDoubleQuote",
                "Tilde",
                "LeftShift",
                "BackslashPipe",
                "W",
                "X",
                "C",
                "V",
                "B",
                "N",
                "M",
                "CommaLeftArrow",
                "PeriodRightArrow",
                "ForwardSlashQuestionMark",
                "RightShift",
                "RightAlt",
                "Space",
                "CapsLock",
                "F1",
                "F2",
                "F3",
                "F4",
                "F5",
                "F6",
                "F7",
                "F8",
                "F9",
                "F10",
                "F11",
                "F12",
                "Up",
                "Down",
                "Right",
                "Left",
                "Home",
                "End",
                "Delete",
                "PageUp",
                "PageDown",
                "Insert",
                "PrintScreen",
                "NumLock",
                "ScrollLock",
                "Menu",
                "WindowsKey",
                "NumpadDivide",
                "NumpadAsterisk",
                "Numpad7",
                "Numpad8",
                "Numpad9",
                "Numpad4",
                "Numpad5",
                "Numpad6",
                "Numpad1",
                "Numpad2",
                "Numpad3",
                "Numpad0",
                "NumpadDelete",
                "NumpadEnter",
                "NumpadPlus",
                "NumpadMinus"
                };
        string[] snippets = { "if(^)\n{\n}", "if(^)\n{\n}\nelse\n{\n}", "for(^;;)\n{\n}", "while(^)\n{\n}", "do${\n^}while();", "switch(^)\n{\n\tcase : break;\n}" };
        string[] declarationSnippets = {
               "public class ^\n{\n}", "private class ^\n{\n}", "internal class ^\n{\n}",
               "public struct ^\n{\n}", "private struct ^\n{\n}", "internal struct ^\n{\n}",
               "public void ^()\n{\n}", "private void ^()\n{\n}", "internal void ^()\n{\n}", "protected void ^()\n{\n}",
               "public ^{ get; set; }", "private ^{ get; set; }", "internal ^{ get; set; }", "protected ^{ get; set; }",
               "public void ^()\n{\n}", "private void ^()\n{\n}", "public string ^()\n{\n}", "private string ^()\n{\n}",
               "public bool ^()\n{\n}", "private bool ^()\n{\n}", "public int ^()\n{\n}", "private int ^()\n{\n}",
               "public double ^()\n{\n}", "private double ^()\n{\n}", "public float ^()\n{\n}", "private float ^()\n{\n}"
               };
        public Form3(Form1 f)
        {
            this.form1 = f;
            InitializeComponent();
        }
        private void button1_Click(object sender, EventArgs e)
        {
            form1.search(true, textBox1.Text);
        }
        private void button2_Click(object sender, EventArgs e)
        {
            form1.search(false, textBox1.Text);
        }
        private void Form3_Load(object sender, EventArgs e)
        {
            BuildAutocompleteMenu();
            textBox1.Text = form1.havewordsearch();
        }
        private void Form3_FormClosed(object sender, FormClosedEventArgs e)
        {
            form1.clearcolor(textBox1.Text);
        }
        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            form1.clearcolor(textBox1.Text);
        }
        private void BuildAutocompleteMenu()
        {
            var items = new List<AutocompleteItem>();

            foreach (var item in snippets)
                items.Add(new SnippetAutocompleteItem(item) { ImageIndex = 1 });
            foreach (var item in declarationSnippets)
                items.Add(new DeclarationSnippet(item) { ImageIndex = 0 });
            foreach (var item in methods)
                items.Add(new MethodAutocompleteItem(item) { ImageIndex = 2 });
            foreach (var item in keywords)
                items.Add(new AutocompleteItem(item));

            items.Add(new InsertSpaceSnippet());
            items.Add(new InsertSpaceSnippet(@"^(\w+)([=<>!:]+)(\w+)$"));
            items.Add(new InsertEnterSnippet());

            //set as autocomplete source
            autocompleteMenu1.SetAutocompleteItems(items);
        }
    }
}
